version: 2

jobs:
    deploy:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package-lock.json" }}

            - run:
                  name: Install dependencies
                  command: npm install

            - save_cache:
                  key: node-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm

            - run:
                  name: Run tests
                  command: npm run test

            - build:
                  name: Build nuxt
                  command: npm run build

workflows:
    version: 2
    ci:
        jobs:
            - deploy
